[[GLEW]]
arch = "i686"
git-tree-sha1 = "764af67563cd721da90e8718b18307e078286127"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "8859e2b32f1798135584350bc4a9d1c06dd82d0aab0e2a14d60e0fef3c198bed"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.i686-linux-musl.tar.gz"
[[GLEW]]
arch = "aarch64"
git-tree-sha1 = "a35314d49649787f41234c4c6bf940d159bbdff5"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "b659c4b37c0513563ce603eeedb0da648a0b0666ec0f5fdc6ddbd11fab3a3571"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.aarch64-linux-musl.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "4f5584ce8c6083c40e9efe34fb81a94419422a1e"
os = "windows"

    [[GLEW.download]]
    sha256 = "4f279fe98a6c8f976f4a898ddd9fa4cde52233b8a4284dfa80514d0ed153c2be"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.i686-w64-mingw32.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "600525fcbb1134d90cf8ab31cbb052aed624bcf8"
os = "windows"

    [[GLEW.download]]
    sha256 = "b541d968a2985e7516c20c34580eacd531ad3204654618270cfa30ee94f44b71"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.x86_64-w64-mingw32.tar.gz"
[[GLEW]]
arch = "armv7l"
git-tree-sha1 = "fd159e3628986f4ce6715dbf2671871e9efcb8f9"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "ef685c4b39ebd2fb288ae5b3651f2a772eb7873f8234a0a8f838067c471fdb49"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[GLEW]]
arch = "armv7l"
git-tree-sha1 = "7cb7ee62f4de81cd86b4b7eb4d13da887462fdb5"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "cdf325b14e8a8fd35029b142d614a864f871c1a78088576973c02d459db1e551"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "93165dc52d8da43958fb76a73a05529726665433"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "fcb32bb97276e998d3ca108d4bf21bfd98d7ad2f6d64536acae3cfbcab7af635"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.i686-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "905273db6b7d1b85331f8165cce1e7614c2af440"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "6c69fddd68c5c8891090a20a7217c759776da6feb660e27dc6eb6f0af727891c"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.x86_64-linux-gnu.tar.gz"
[[GLEW]]
arch = "powerpc64le"
git-tree-sha1 = "62a3fdfb4772064c545cba1cd094db308b073751"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "03be76d26d8323dac576b9e1cdb18cd4492cd515ea4d9be0bf83a99a1fa7a644"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "40cd7667515e72884f36b419638060064d2212f7"
os = "macos"

    [[GLEW.download]]
    sha256 = "113f7ea814c234e3b92a45725f57fc1b8ac05f5e1e77de0403a5ca701fbbb323"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.x86_64-apple-darwin14.tar.gz"
[[GLEW]]
arch = "aarch64"
git-tree-sha1 = "ef30d6e5bfbe4f36f64b7b5fd49ecf7508a0c6ae"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "6a1bbabeb22846106d5c4a2bab152583bf4735739d67c1cc32d565687c811cdf"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.aarch64-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "8f8e1d46d732e1edb89c1e406ac587a0a27dcf4d"
os = "freebsd"

    [[GLEW.download]]
    sha256 = "0c568ae746c4738c0c7e7607004c609286f50da8298f374ce1c36cc6f51eca5f"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "4eb75900b2ba79320ee62f7b84faf08f064a9823"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "5daa5fbd8d8b1f0d91cbede6c10b0ebcd1a293bbc477355595fa2136ec7f1d43"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+3/GLEW.v2.1.0.x86_64-linux-musl.tar.gz"
