[[GLEW]]
arch = "aarch64"
git-tree-sha1 = "adac7c401f6e08ba9e5fb4e5af8ae3a99b4fbf3f"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "4887cd71a9ca0cc18321624996852f9611f467ad7e3c54f35bca455f72bc0ef6"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.aarch64-linux-gnu.tar.gz"
[[GLEW]]
arch = "aarch64"
git-tree-sha1 = "c5df90463e1fca035ee0dffc5142f31d133632ae"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "2e8b7717540993d00e21f92fa1ab10f6fdb36a8e6d8514403ddbf89aff1a0dc4"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.aarch64-linux-musl.tar.gz"
[[GLEW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4eb39358bba8d1a90bcde73713b09b5d11079e70"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "8964813ceca19f0be83548ae9591bf304c45c4e5a8233fc8963e8ee86d93ede9"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[GLEW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "554c2c84c3118c0e9a8c65088c7bafd3fa67e0c7"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "84a4c08d1c8f0ec0fdae258566d79397b82ee744e5436b7c4ddc6e5fca0c0664"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "2f64c092015ab3bbfa140620b559076770d6f2d8"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "ee2ff9cf1d435ceaacea2ec96948e4f9cf271e0bbbfd011a953a8d62a42c2614"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.i686-linux-gnu.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "a362db4cbdce05df840b18ca0db318ef656cd627"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "6b0613b68090dbd2f98a3851535a65f321b1bb346508880396565906c66ae9ca"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.i686-linux-musl.tar.gz"
[[GLEW]]
arch = "i686"
git-tree-sha1 = "cb67fc2d651562c59872ff23920f4e76ea63a1ba"
os = "windows"

    [[GLEW.download]]
    sha256 = "008333f9840bc73084a0b1cf0e062d8fbeb8b7c16d01ecc4d3d376f8778d4eeb"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.i686-w64-mingw32.tar.gz"
[[GLEW]]
arch = "powerpc64le"
git-tree-sha1 = "e51eada6087f18b48587cdbc4620851329565eb3"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "45dfc5425db0989c56f176df7cce865bede8efeeb73a6aaed42102b390521e33"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "33cc8691318442e1d9dce1d824ffd47a36751e35"
os = "macos"

    [[GLEW.download]]
    sha256 = "c5b69f5891b6b8f09f120e00cbdbc0e1d08ebf948f9c8aa401c274b787d93feb"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.x86_64-apple-darwin.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "f3046f144fed1ff9f62a61ccd9f7ed812f3113a4"
libc = "glibc"
os = "linux"

    [[GLEW.download]]
    sha256 = "62772fe0738d80d21bac6d89579a05de43eea6f0bc6fde5edc18d55bf1e97310"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.x86_64-linux-gnu.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "64bf1715b08da7bff8e0acf4001afc5c75f36e99"
libc = "musl"
os = "linux"

    [[GLEW.download]]
    sha256 = "60866ef78fb537f1e81852d38359931d55361c3c0cb68bc7ec3a1a5de23c9662"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.x86_64-linux-musl.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "9bcbea87397e65244c86416985c93804a6b553a5"
os = "freebsd"

    [[GLEW.download]]
    sha256 = "5168ed418f0b13176a47aa726aa6b3e352092afdc8d7a83574495c1460a84672"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.x86_64-unknown-freebsd.tar.gz"
[[GLEW]]
arch = "x86_64"
git-tree-sha1 = "f61327c71df7f8f245118eab925d8b7add61c541"
os = "windows"

    [[GLEW.download]]
    sha256 = "c47811e0f3204f3e54e20f6744c447be59cbc9d988051b3ec338ba8c9c76b3d3"
    url = "https://github.com/JuliaBinaryWrappers/GLEW_jll.jl/releases/download/GLEW-v2.1.0+4/GLEW.v2.1.0.x86_64-w64-mingw32.tar.gz"
