# Autogenerated wrapper script for GLEW_jll for x86_64-w64-mingw32
export libGLEW

using Libglvnd_jll
using Xorg_libXi_jll
JLLWrappers.@generate_wrapper_header("GLEW")
JLLWrappers.@declare_library_product(libGLEW, "glew32.dll")
function __init__()
    JLLWrappers.@generate_init_header(Libglvnd_jll, Xorg_libXi_jll)
    JLLWrappers.@init_library_product(
        libGLEW,
        "bin\\glew32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
